### ISSUE TITLE
Re-create jitpack-zoom-us

### ISSUE THREAD

**Issue by mieszko4** [zoom-us-community/jitpack-zoom-us#1]
Steps I did:

1. Prepare
```sh
brew install git-filter-repo
git clone git@github.com:zoom-us-community/jitpack-zoom-us.git
cd jitpack-zoom-us/
git filter-repo --invert-paths --path libs/commonlib.aar
git filter-repo --invert-paths --path libs/mobilertc.aar
mkdir libs
touch libs/.gitkeep
git add libs/
git commit
git for-each-ref --format="delete %(refname)" refs/original | git update-ref --stdin
git reflog expire --expire=now --all
rm -fr .git/lfs/
git lfs uninstall
git lfs install
```

2. Backup and remove `jitpack-zoom-us`
3. Create `jitpack-zoom-us`
4. Push back
```sh
git push origin --force --all
git push origin --force --tags
```

**NOTE: Unfortunately, it removed previous issues, PRs, forks - but the history of committers is kept.**

<details id="screenshots">
<summary>SCREENSHOTS of previous repo</summary>
<img width="1254" alt="Screenshot 2023-03-12 at 19 10 05" src="https://user-images.githubusercontent.com/3238370/225452077-8be81296-f103-4450-9e07-795406e3a1b6.png">
<img width="957" alt="Screenshot 2023-03-12 at 19 10 21" src="https://user-images.githubusercontent.com/3238370/225452083-c718aa1e-ce7f-4bd4-a131-cae1435ee6ab.png">
<img width="970" alt="Screenshot 2023-03-12 at 19 10 32" src="https://user-images.githubusercontent.com/3238370/225452086-2e1476b5-de12-48a8-a80b-fb531599602f.png">
<img width="958" alt="Screenshot 2023-03-12 at 19 10 41" src="https://user-images.githubusercontent.com/3238370/225452089-97bc7475-95dc-4605-a035-fc85ea61c1eb.png">
<img width="953" alt="Screenshot 2023-03-12 at 19 10 50" src="https://user-images.githubusercontent.com/3238370/225452091-388cee0f-acae-4d9a-8774-794b23b1f8dc.png">
<img width="975" alt="Screenshot 2023-03-12 at 19 10 56" src="https://user-images.githubusercontent.com/3238370/225452096-26e37ee9-32ed-4103-80a4-7eaffae995c5.png">
<img width="973" alt="Screenshot 2023-03-12 at 19 11 01" src="https://user-images.githubusercontent.com/3238370/225452098-6d3901cf-16ef-46f2-8da9-9a702b25d7f1.png">
<img width="973" alt="Screenshot 2023-03-12 at 19 11 05" src="https://user-images.githubusercontent.com/3238370/225452100-637aef32-d300-4590-bcf3-647a184ec21a.png">
<img width="1024" alt="Screenshot 2023-03-12 at 19 12 22" src="https://user-images.githubusercontent.com/3238370/225452104-798f241c-4722-4592-8038-480915519fba.png">
<img width="1319" alt="Screenshot 2023-03-12 at 19 13 56" src="https://user-images.githubusercontent.com/3238370/225452110-17f157fa-a22e-42d8-8691-60584c9ab9bf.png">
<img width="1321" alt="Screenshot 2023-03-12 at 19 14 01" src="https://user-images.githubusercontent.com/3238370/225452111-f1cc2387-8014-4c6e-ac38-0d22e5939c0f.png">
<img width="1340" alt="Screenshot 2023-03-12 at 19 14 31" src="https://user-images.githubusercontent.com/3238370/225452115-e12851af-78b6-4a96-a9f7-92a1767dd749.png">
<img width="1310" alt="Screenshot 2023-03-12 at 19 14 53" src="https://user-images.githubusercontent.com/3238370/225452121-f8512980-e610-45cd-8710-10fdf06d5579.png">
<img width="958" alt="Screenshot 2023-03-12 at 19 14 57" src="https://user-images.githubusercontent.com/3238370/225452122-671bcb4d-92e5-4ee7-945b-de93eed05a89.png">
<img width="1349" alt="Screenshot 2023-03-12 at 19 15 08" src="https://user-images.githubusercontent.com/3238370/225452126-100c4742-6cbf-4a9a-a770-cb0c81ba5170.png">
<img width="1343" alt="Screenshot 2023-03-12 at 19 15 23" src="https://user-images.githubusercontent.com/3238370/225452128-a8ef8198-0e9c-459b-8972-362b0787a9ea.png">
<img width="1389" alt="Screenshot 2023-03-12 at 19 16 12" src="https://user-images.githubusercontent.com/3238370/225452131-1f53408c-6be8-4d1e-8869-56744c674978.png">
<img width="1328" alt="Screenshot 2023-03-12 at 19 16 26" src="https://user-images.githubusercontent.com/3238370/225452133-0326d1e9-ffb7-4ca5-b572-9a4c98868f32.png">
<img width="1223" alt="Screenshot 2023-03-12 at 19 18 42" src="https://user-images.githubusercontent.com/3238370/225452137-19b2c16f-7e19-4880-9c65-8691f1c6d558.png">
<img width="969" alt="Screenshot 2023-03-12 at 19 48 26" src="https://user-images.githubusercontent.com/3238370/225452141-0d603e42-9ab2-4c75-8f9c-62fbcae65387.png">
</details>

**Comment by mieszko4** [comment]
@zvs001 
[Storage](https://github.com/organizations/zoom-us-community/settings/billing) went down to 0 as expected:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/3238370/224565923-d5ba0626-5a7a-4b33-ab21-bc763de1f063.png">

We should be good for adding another 5 versions in LFS until next repo recreation.

**Comment by zvs001** [comment]
We don't have any versions working now.
I see files were deleted from all tags, so jitpack package is not working now.
It would be good to keep at least few latest versions

**Comment by zvs001** [comment]
@mieszko4 it is pretty critical. Devs will not be able to build their app anymore.
We need to add at least one working version

**Comment by mieszko4** [comment]
> We don't have any versions working now. I see files were deleted from all tags, so jitpack package is not working now. It would be good to keep at least few latest versions

Oh, I thought that yo saw my comments in the deleted repository. I added the screenshots now in [this PR description ()](https://github.com/zoom-us-community/jitpack-zoom-us/issues/1#screenshots)

**Comment by mieszko4** [comment]
> @mieszko4 it is pretty critical. Devs will not be able to build their app anymore. We need to add at least one working version

@zvs001 I do not think we need to do anything. As I mentioned earlier (in deleted repo) based on https://jitpack.io/docs/FAQ/
> What happens if a tag or repository is deleted on GitHub?
> If the project was already built then JitPack will continue serving the existing artifacts. It will not rebuild the project at the new tag. In case you need to redo a release the best option is to create a new version on GitHub.

jitpack will continue serving the data because it does not reference GitHub once the build is completed.

I also tried the app after removing gradle cache and it is all good.

**Comment by zvs001** [comment]
@mieszko4 interesting. I didn't know they serve versions.
Looks like we can drop tags also.
