### ISSUE TITLE
LFS quota exceeded

### ISSUE THREAD

**Issue by mieszko4** [zoom-us-community/jitpack-zoom-us#11]
I cannot upload 5.13.1 because of this error:
> Error downloading object: libs/commonlib.aar (02055f0): Smudge error: Error downloading libs/commonlib.aar (02055f0a85f414de016fe0a1e5af6c3df21f482e208e3b6c64b59bed60edc746): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

@zvs001 Since you are the owner of this repo, could you see what the problem is?

**Comment by zvs001** [comment]
@mieszko4 I also added you as an owner.

Issue is that github have only 1GB limit for files that we can store. So we have to upgrade plan to get more space.

**Comment by mieszko4** [comment]
I added 5$

**Comment by zvs001** [comment]
@mieszko4 I sent message to zoom 3 weeks ago. I expected they can take responsibility since we help them.
Seems we were ignored. I didn't receive any answer.

**Comment by mieszko4** [comment]
Thnx! Perhaps we can just remove old unsupported versions from LFS for now?

**Comment by zvs001** [comment]
Yes. We can remove first 2 versions, since they are deprecated by zoom. 
But it not really create difference.

**Comment by mieszko4** [comment]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/3238370/223014459-738fa555-da90-4abc-80de-e9528e6c3a7f.png">

I see, 2 first versions would not be enough. Also, the problem is the bandwidth. I am not sure why over 1GB was used - I would assume JitPack caches it?
Anyway, the limits are 1GB for both according to:
> Without a data pack, every account receives 1 GB of free storage and 1 GB of free bandwidth

**Comment by zvs001** [comment]
As I know, when we build project jitpack will clone repository to local machine. For subsequent runs it can use local cache.
Jitpack service is not really store any data.

**Comment by mieszko4** [comment]
Based on https://support.zoom.us/hc/en-us/articles/360059429231-Zoom-Software-Quarterly-Lifecycle-Policy, current enforcement version is `5.10.3` which will become `5.11.3` in May.

So we can safely remove from LFS `5.9.6` and below which will be 5 versions. This should be enough to be below 1GB quota.

I will do remove these version from the repo now using https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage

**Comment by mieszko4** [comment]
> I will do remove these version from the repo now using https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage

It looks like we need to delete and create a new repository in order to do completely remove the count on LFS (https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository)

**Comment by mieszko4** [comment]
Based on https://jitpack.io/docs/FAQ/:
> What happens if a tag or repository is deleted on GitHub?

> If the project was already built then JitPack will continue serving the existing artifacts. It will not rebuild the project at the new tag. In case you need to redo a release the best option is to create a new version on GitHub.

We should be fine with removing anything from GIT LFS once it is published on JitPack so we should be fine with re-creating the repo with no LFS and add it only when releasing new version.
