### ISSUE TITLE
New version v5.9.1.3674

### ISSUE THREAD

**Issue by pmogollons** [zoom-us-community/jitpack-zoom-us#5]
Hi @zvs001,

There is a new version of the iOS SDK that might help fix some issues in the react-native packages. Do you think you can update it or maybe I can make a PR and you can review and merge it?

https://marketplace.zoom.us/docs/changelog#publications/android-meeting-sdk-v5-9-1-3674-patch

Thanks.

**Comment by zvs001** [comment]
We added 2 new versions:
`implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.9.1.3674'`
`implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.9.1.3662`

You can try.

**Comment by pmogollons** [comment]
Thanks man.
